###################################################### spark ######################################################
spark:
  image:
    registry: docker.io
    repository: bitnami/spark
    tag: 3.5.0
  enabled: true
  worker:
    memoryLimit: 1024M
    autoscaling:
      minReplicas: 1
      maxReplicas: 2

###################################################### jupyterhub ######################################################
jupyterhub:
  enabled: true
  hub:
    service:
      type: ClusterIP
  singleuser:
    image:
      name: jupyter/pyspark-notebook
      tag: x86_64-spark-3.5.0
    networkPolicy:
      enabled: false


###################################################### Minio ######################################################
minio:
  enabled: true
  mode: standalone
  existingSecret: minio-root-secret
  replicas: 2
  # https://github.com/minio/console/issues/2539#issuecomment-1619211962
  environment:
    MINIO_BROWSER_LOGIN_ANIMATION: "off"
  metrics:
    serviceMonitor:
      enabled: true
  resources:
    requests:
      memory: 1Gi
      cpu: 250m
    limits:
      memory: 2Gi
      cpu: 500m
  persistence:
    pvc:
      spec:
        accessModes:
        - ReadWriteOnce
        resources: 
          requests:
            storage: 20Gi
          storageClassName: microk8s-hostpath
  users:
    - accessKey: reidx
      policy: readwrite
      secretKey: f27
      # Use a secure password
      existingSecret: analyst-s3-access-key
      existingSecretKey: password
  svcaccts:
    - accessKey: reidx-svcacct
      secretKey: f27-svcacct
      # Use a secure password
      existingSecret: analyst-s3-access-key
      existingSecretKey: secretKey
      user: reidx
  buckets:
    - name: "bronze"
    - name: "silver"
    - name: "gold"
    - name: "fallback"
